### ISSUE TITLE
Scrollable only applies to children widgets

### ISSUE THREAD

**Issue by BaudouinCS** [lewiseman/circular_motion#1]
Hi!

First of all, thanks a lot for this package! Very useful, and all the others I tried had too many issues or were just not what I was looking for.

When scrolling the circle of widgets, I figured out the scroll works only when the `onVerticalDrag` gesture started on one of the children widgets. It's especially bad for small children such as a list of icons or small containers, since it's quite hard to get it right.

I would suggest extending the scroll listening to the whole circle instead of just the children, or at least us give a parameter saying we want this kind of behavior. Could divide the circle formed by this package in 2 halves (so 4 quarters), and depending of which quarter the scroll got initiated and if it's horizontal/vertical scroll, rotate the circle appropriately?

Also, if in the very likely case the children are Text widgets (for a circular menu for example), we should be able to scroll the circle the same even if we initiate the scroll at the end of the Text widget too and not only inside the circle, so it would actually be in addition of the current mechanics.

Looking forward hearing what you think about this,
Regards.

**Comment by lewiseman** [comment]
@BaudouinCS Thank you for using using the package.
Yeah , the scroll only works for on individual children . I hadn't given consideration to smaller widgets as you have mentioned .
I will add the option to specify the desired effect . I will try and add this either this week or latest next week in a new release.

For the other issues/suggestions please consider opening separate issues and I will have a look at them .

Thanks again for your feedback .

**Comment by lewiseman** [comment]
this is now fixed in version 0.0.3

**Comment by lewiseman** [comment]
use 
` behavior: HitTestBehavior.translucent,`
